#!/usr/bin/env python3
"""校验 poetry.lock 与 pyproject.toml 是否已经同步。

用法（CI 中由 `.github/workflows/ci.yml` 调用，作为 `poetry check --lock` 的补充）：

    poetry check --lock   # 根 pyproject.toml 的 content-hash
    cp poetry.lock "$RUNNER_TEMP/poetry.lock.committed"
    poetry lock
    python .github/scripts/check_poetry_lock.py "$RUNNER_TEMP/poetry.lock.committed" poetry.lock

`src/pyproject.toml` 的约束不在 content-hash 覆盖范围内，只能这样校验：`poetry lock` 只会补齐
pyproject 变更所必需的解析结果，不会升级已锁定的包（那是 `poetry update` 的行为），
如果解析前后已锁定的包集合不同，说明提交上来的 lock 是过期的。

这里只比较「包名 -> 已锁定版本」，不比较文件文本：不同 Poetry 版本会把 `!=1.2` 这类约束
规范化成 `<1.2 || >1.2`、并改写文件头的 "generated by"，这些都不改变已解析的版本，
按文本 diff 会把正常的 lock 判成过期。
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_NAME = re.compile(r'^name = "(.+)"$', re.MULTILINE)
_VERSION = re.compile(r'^version = "(.+)"$', re.MULTILINE)


def locked_versions(path: Path) -> dict[str, tuple[str, ...]]:
    """读取 lock 文件，返回每个包已锁定的版本（同名多版本时按版本排序）。"""
    versions: dict[str, list[str]] = {}
    for block in path.read_text(encoding="utf-8").split("[[package]]")[1:]:
        name = _NAME.search(block)
        version = _VERSION.search(block)
        if name and version:
            versions.setdefault(name.group(1), []).append(version.group(1))
    return {name: tuple(sorted(found)) for name, found in versions.items()}


def main() -> int:
    committed = locked_versions(Path(sys.argv[1]))
    resolved = locked_versions(Path(sys.argv[2]))
    if committed == resolved:
        print("poetry.lock 与 pyproject.toml 一致")
        return 0

    for name in sorted(set(committed) | set(resolved)):
        if committed.get(name) != resolved.get(name):
            print(f"poetry.lock 需要更新：{name}: {committed.get(name, ())} -> {resolved.get(name, ())}")
    print("请在本机运行 `poetry lock`，并把生成的 poetry.lock 一起提交。")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
