"""empty message

迁移 ID: 00bcd82b1045
父迁移: 078c40497030
创建时间: 2026-05-04 23:10:49.011369

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "00bcd82b1045"
down_revision: str | Sequence[str] | None = "078c40497030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_message_summary_groupdailysummary",
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("group_id", "date", name=op.f("pk_nonebot_plugin_message_summary_groupdailysummary")),
        info={"bind_key": "nonebot_plugin_message_summary"},
    )
    op.create_table(
        "nonebot_plugin_message_summary_mvprecord",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.Column("mvp_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "group_id", name=op.f("pk_nonebot_plugin_message_summary_mvprecord")),
        info={"bind_key": "nonebot_plugin_message_summary"},
    )
    # with op.batch_alter_table('nonebot_plugin_chat_messagequeuecache', schema=None) as batch_op:
    #     batch_op.alter_column('message_hash',
    #            existing_type=sa.NUMERIC(precision=32),
    #            type_=sa.BINARY(length=32),
    #            existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_message_summary_groupmessage", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_message_summary_groupmessage", schema=None) as batch_op:
        batch_op.drop_column("user_id")

    # with op.batch_alter_table('nonebot_plugin_chat_messagequeuecache', schema=None) as batch_op:
    #     batch_op.alter_column('message_hash',
    #            existing_type=sa.BINARY(length=32),
    #            type_=sa.NUMERIC(precision=32),
    #            existing_nullable=False)

    op.drop_table("nonebot_plugin_message_summary_mvprecord")
    op.drop_table("nonebot_plugin_message_summary_groupdailysummary")
    # ### end Alembic commands ###
