"""empty message

迁移 ID: 01cf42b0eb35
父迁移: 5e5d93afbc20
创建时间: 2026-02-13 14:07:24.081801

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "01cf42b0eb35"
down_revision: str | Sequence[str] | None = "5e5d93afbc20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_chatgroup", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blocked_keyword", sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_chatgroup", schema=None) as batch_op:
        batch_op.drop_column("blocked_keyword")

    # ### end Alembic commands ###
