"""empty message

迁移 ID: 02b1cfe2ff47
父迁移: 0fbe94039ef4
创建时间: 2026-05-31 11:34:11.494591

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '02b1cfe2ff47'
down_revision: str | Sequence[str] | None = '0fbe94039ef4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_status_report_commandusage',
    sa.Column('command_name', sa.String(length=256), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('command_name', name=op.f('pk_nonebot_plugin_status_report_commandusage')),
    info={'bind_key': 'nonebot_plugin_status_report'}
    )
    op.create_table('nonebot_plugin_status_report_exceptionrecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exception', sa.Text(), nullable=False),
    sa.Column('session', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('bot_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_status_report_exceptionrecord')),
    info={'bind_key': 'nonebot_plugin_status_report'}
    )
    op.create_table('nonebot_plugin_status_report_handlerresultrecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command_name', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('matcher', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_status_report_handlerresultrecord')),
    info={'bind_key': 'nonebot_plugin_status_report'}
    )
    op.create_table('nonebot_plugin_status_report_openaihistoryrecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('identify', sa.String(length=256), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_status_report_openaihistoryrecord')),
    info={'bind_key': 'nonebot_plugin_status_report'}
    )
    with op.batch_alter_table('nonebot_plugin_chat_messagequeuecache', schema=None) as batch_op:
        batch_op.alter_column('message_hash',
               existing_type=sa.NUMERIC(precision=32),
               type_=sa.BINARY(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_messagequeuecache', schema=None) as batch_op:
        batch_op.alter_column('message_hash',
               existing_type=sa.BINARY(length=32),
               type_=sa.NUMERIC(precision=32),
               existing_nullable=False)

    op.drop_table('nonebot_plugin_status_report_openaihistoryrecord')
    op.drop_table('nonebot_plugin_status_report_handlerresultrecord')
    op.drop_table('nonebot_plugin_status_report_exceptionrecord')
    op.drop_table('nonebot_plugin_status_report_commandusage')
    # ### end Alembic commands ###
