"""empty message

迁移 ID: 037dfa9894a4
父迁移: fc68a41a83f3
创建时间: 2025-08-05 22:38:06.084176

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "037dfa9894a4"
down_revision: str | Sequence[str] | None = "fc68a41a83f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_everyday_wife_wifedata",
        sa.Column("id_", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("wife_id", sa.String(length=128), nullable=False),
        sa.Column("queried", sa.Boolean(), nullable=False),
        sa.Column("generate_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_everyday_wife_wifedata")),
        info={"bind_key": "nonebot_plugin_everyday_wife"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_everyday_wife_wifedata")
    # ### end Alembic commands ###
