"""empty message

迁移 ID: 0778ae595d24
父迁移: 037dfa9894a4
创建时间: 2025-08-22 16:28:17.213888

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0778ae595d24"
down_revision: str | Sequence[str] | None = "037dfa9894a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_openai_gptuser")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_openai_gptuser",
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("session_id", sa.INTEGER(), nullable=True),
        sa.Column("used_token", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_openai_gptuser")),
    )
    # ### end Alembic commands ###
