"""empty message

迁移 ID: 078c40497030
父迁移: d025fa75554d
创建时间: 2026-04-30 19:55:41.100116

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '078c40497030'
down_revision: str | Sequence[str] | None = 'd025fa75554d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_everyday_wife_wifedata',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('wife_id', sa.String(length=128), nullable=False),
    sa.Column('queried', sa.Boolean(), nullable=False),
    sa.Column('generate_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk_nonebot_plugin_everyday_wife_wifedata')),
    info={'bind_key': 'nonebot_plugin_everyday_wife'}
    )
    with op.batch_alter_table('nonebot_plugin_chat_messagequeuecache', schema=None) as batch_op:
        batch_op.alter_column('message_hash',
               existing_type=sa.NUMERIC(precision=32),
               type_=sa.BINARY(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_messagequeuecache', schema=None) as batch_op:
        batch_op.alter_column('message_hash',
               existing_type=sa.BINARY(length=32),
               type_=sa.NUMERIC(precision=32),
               existing_nullable=False)

    op.drop_table('nonebot_plugin_everyday_wife_wifedata')
    # ### end Alembic commands ###
