"""empty message

迁移 ID: 09737ac938df
父迁移: 31b8bd465866
创建时间: 2024-08-10 00:46:51.485034

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '09737ac938df'
down_revision: str | Sequence[str] | None = '31b8bd465866'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_finding_the_trail_userpoint',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('exchanged', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_finding_the_trail_userpoint')),
    info={'bind_key': 'nonebot_plugin_finding_the_trail'}
    )
    op.drop_table('nonebot_plugin_render_themeconfig')
    op.drop_table('nonebot_plugin_larklang_languageconfig')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_larklang_languageconfig',
    sa.Column('user_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=16), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nonebot_plugin_render_themeconfig',
    sa.Column('user_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('theme', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('nonebot_plugin_finding_the_trail_userpoint')
    # ### end Alembic commands ###
