"""add trace_id to MessageQueueCache

迁移 ID: 0c7846aeaa7b
父迁移: 69e42fc34f38
创建时间: 2026-05-17 22:39:11.627485

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "0c7846aeaa7b"
down_revision: str | Sequence[str] | None = "69e42fc34f38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trace_id", sa.String(length=64), nullable=True))
        batch_op.alter_column(
            "message_hash", existing_type=sa.NUMERIC(precision=32), type_=sa.BINARY(length=32), existing_nullable=False
        )

    with op.batch_alter_table("nonebot_plugin_fight_character", schema=None) as batch_op:
        batch_op.alter_column("buff_list", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)
        batch_op.alter_column("equipment", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)
        batch_op.alter_column("talent_level", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_fight_equipmentdata", schema=None) as batch_op:
        batch_op.alter_column("gains", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_fight_playerteam", schema=None) as batch_op:
        batch_op.alter_column("character_list", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_fight_playerteam", schema=None) as batch_op:
        batch_op.alter_column("character_list", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_fight_equipmentdata", schema=None) as batch_op:
        batch_op.alter_column("gains", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_fight_character", schema=None) as batch_op:
        batch_op.alter_column("talent_level", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)
        batch_op.alter_column("equipment", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)
        batch_op.alter_column("buff_list", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
        batch_op.alter_column(
            "message_hash", existing_type=sa.BINARY(length=32), type_=sa.NUMERIC(precision=32), existing_nullable=False
        )
        batch_op.drop_column("trace_id")

    # ### end Alembic commands ###
