"""empty message

迁移 ID: 10066cac30c2
父迁移: 550d33d67611
创建时间: 2025-08-24 12:54:40.730797

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "10066cac30c2"
down_revision: str | Sequence[str] | None = "550d33d67611"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_memoryedge", schema=None) as batch_op:
        batch_op.alter_column("hash_value", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_chat_memorynode", schema=None) as batch_op:
        batch_op.alter_column("hash_value", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_memorynode", schema=None) as batch_op:
        batch_op.alter_column("hash_value", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_chat_memoryedge", schema=None) as batch_op:
        batch_op.alter_column("hash_value", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)

    # ### end Alembic commands ###
