"""empty message

迁移 ID: 15f6ccca4a5d
父迁移: 10066cac30c2
创建时间: 2025-09-05 23:02:19.907202

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "15f6ccca4a5d"
down_revision: str | Sequence[str] | None = "10066cac30c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkuser_userdata", schema=None) as batch_op:
        batch_op.alter_column("register_time", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkuser_userdata", schema=None) as batch_op:
        batch_op.alter_column("register_time", existing_type=sa.DATETIME(), nullable=True)

    # ### end Alembic commands ###
