"""empty message

迁移 ID: 2496bf44d32c
父迁移: 898d6147c141
创建时间: 2024-11-09 07:59:54.082070

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2496bf44d32c'
down_revision: str | Sequence[str] | None = '898d6147c141'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_wakatime_user')
    with op.batch_alter_table('nonebot_plugin_larkuser_userdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_larkuser_userdata', schema=None) as batch_op:
        batch_op.drop_column('config')

    op.create_table('nonebot_plugin_wakatime_user',
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=256), nullable=False),
    sa.Column('expired_at', sa.DOUBLE(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='pk_nonebot_plugin_wakatime_user')
    )
    # ### end Alembic commands ###
