"""empty message

迁移 ID: 24c7dc8e7e67
父迁移: a1b2c3d4e5f6
创建时间: 2026-01-24 23:33:36.695599

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "24c7dc8e7e67"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_chat_chatuser")
    op.drop_table("nonebot_plugin_chat_sessionmessage")
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_meme", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("meme_text", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("emotion", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("labels", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("context_keywords", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.drop_column("context_keywords")
        batch_op.drop_column("labels")
        batch_op.drop_column("emotion")
        batch_op.drop_column("meme_text")
        batch_op.drop_column("is_meme")

    op.create_table(
        "nonebot_plugin_chat_sessionmessage",
        sa.Column("id_", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("role", sa.VARCHAR(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_chat_sessionmessage")),
    )
    op.create_table(
        "nonebot_plugin_chat_chatuser",
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("latest_chat", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_chat_chatuser")),
    )
    # ### end Alembic commands ###
