"""empty message

迁移 ID: 2cd80b434c9c
父迁移: b29767cc9c3d
创建时间: 2026-03-20 14:03:36.283489

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "2cd80b434c9c"
down_revision: str | Sequence[str] | None = "b29767cc9c3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_mainsessiondata",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("data_json", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=False),
        sa.Column("updated_time", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_nonebot_plugin_chat_mainsessiondata")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_chat_mainsessiondata")
    # ### end Alembic commands ###
