"""empty message

迁移 ID: 2d37cbcd4709
父迁移: 36722c1b0659
创建时间: 2025-07-12 02:14:34.477977

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2d37cbcd4709'
down_revision: str | Sequence[str] | None = '36722c1b0659'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_chatterbox_ranking_groupchatterbox',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk_nonebot_plugin_chatterbox_ranking_groupchatterbox')),
    info={'bind_key': 'nonebot_plugin_chatterbox_ranking'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_chatterbox_ranking_groupchatterbox')
    # ### end Alembic commands ###
