"""empty message

迁移 ID: 31b8bd465866
父迁移: 9537565f5d31
创建时间: 2024-07-22 22:19:35.174976

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "31b8bd465866"
down_revision: str | Sequence[str] | None = "9537565f5d31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_wakatime_user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("access_token", sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column("expired_at", sa.Double(), nullable=False))
        batch_op.drop_column("user_name")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_wakatime_user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_name", mysql.VARCHAR(length=256), nullable=False))
        batch_op.drop_column("expired_at")
        batch_op.drop_column("access_token")

    # ### end Alembic commands ###
