"""empty message

迁移 ID: 36722c1b0659
父迁移: 9c6d165934aa
创建时间: 2025-07-11 14:21:23.629218

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "36722c1b0659"
down_revision: str | Sequence[str] | None = "9c6d165934aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_message_summary_groupmessage",
        sa.Column("id_", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("sender_nickname", sa.String(length=128), nullable=False),
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_message_summary_groupmessage")),
        info={"bind_key": "nonebot_plugin_message_summary"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_message_summary_groupmessage")
    # ### end Alembic commands ###
