"""empty message

迁移 ID: 3875dac35e58
父迁移: 24c7dc8e7e67
创建时间: 2026-01-25 13:33:07.981017

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3875dac35e58'
down_revision: str | Sequence[str] | None = '24c7dc8e7e67'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_sticker', schema=None) as batch_op:
        batch_op.drop_column('is_meme')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_meme', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
