"""empty message

迁移 ID: 3bab0285033f
父迁移: 44966c3d2398
创建时间: 2025-10-02 13:42:53.119347

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3bab0285033f'
down_revision: str | Sequence[str] | None = '44966c3d2398'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_chat_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('created_time', sa.Float(), nullable=False),
    sa.Column('expire_time', sa.Float(), nullable=True),
    sa.Column('hash_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_chat_note')),
    info={'bind_key': 'nonebot_plugin_chat'}
    )
    with op.batch_alter_table('nonebot_plugin_chat_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_chat_note_context_id'), ['context_id'], unique=False)

    op.drop_table('nonebot_plugin_larkcave_groupdata')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_larkcave_groupdata',
    sa.Column('group_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_use', sa.DATETIME(), nullable=False),
    sa.Column('cool_down_time', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_nonebot_plugin_larkcave_groupdata'))
    )
    with op.batch_alter_table('nonebot_plugin_chat_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_chat_note_context_id'))

    op.drop_table('nonebot_plugin_chat_note')
    # ### end Alembic commands ###
