"""empty message

迁移 ID: 3ee8b001fa91
父迁移: acd339d6faf3
创建时间: 2026-07-17 22:54:21.278143

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "3ee8b001fa91"
down_revision: str | Sequence[str] | None = "acd339d6faf3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_bots_group_bind",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_qq_number", sa.String(length=64), nullable=True),
        sa.Column("group_openid", sa.String(length=128), nullable=True),
        sa.Column("bind_code", sa.String(length=32), nullable=True),
        sa.Column("bind_code_created_at", sa.DateTime(), nullable=True),
        sa.Column("bound_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_bots_group_bind")),
        sa.UniqueConstraint("group_openid"),
        sa.UniqueConstraint("group_qq_number"),
        info={"bind_key": "nonebot_plugin_bots"},
    )
    op.drop_table("nonebot_plugin_chat_mainsessionactionhistory")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_mainsessionactionhistory",
        sa.Column("id_", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("start_time", mysql.DATETIME(), nullable=False),
        sa.Column("end_time", mysql.DATETIME(), nullable=True),
        sa.Column("action", mysql.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("nonebot_plugin_bots_group_bind")
    # ### end Alembic commands ###
