"""empty message

迁移 ID: 44966c3d2398
父迁移: 4d490b585855
创建时间: 2025-10-01 04:38:16.104598

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "44966c3d2398"
down_revision: str | Sequence[str] | None = "4d490b585855"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkcave_imagedata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("p_hash", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkcave_imagedata", schema=None) as batch_op:
        batch_op.drop_column("p_hash")

    # ### end Alembic commands ###
