"""empty message

迁移 ID: 4d490b585855
父迁移: 849b5b127800
创建时间: 2025-09-19 13:15:46.475759

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4d490b585855'
down_revision: str | Sequence[str] | None = '849b5b127800'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('remove_removedcave', 'nonebot_plugin_larkcave_removedcave')
    op.rename_table('comment_commentdata', 'nonebot_plugin_larkcave_commentdata')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('nonebot_plugin_larkcave_removedcave', 'remove_removedcave')
    op.rename_table('nonebot_plugin_larkcave_commentdata', 'comment_commentdata')
    # ### end Alembic commands ###
