"""empty message

迁移 ID: 550d33d67611
父迁移: 0778ae595d24
创建时间: 2025-08-23 01:02:03.541317

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "550d33d67611"
down_revision: str | Sequence[str] | None = "0778ae595d24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_memoryedge",
        sa.Column("source", sa.String(length=256), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=False),
        sa.Column("context_id", sa.String(length=128), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.Float(), nullable=False),
        sa.Column("last_modified", sa.Float(), nullable=False),
        sa.Column("hash_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("source", "target", "context_id", name=op.f("pk_nonebot_plugin_chat_memoryedge")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    op.create_table(
        "nonebot_plugin_chat_memorynode",
        sa.Column("concept", sa.String(length=256), nullable=False),
        sa.Column("context_id", sa.String(length=128), nullable=False),
        sa.Column("memory_items", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("created_time", sa.Float(), nullable=False),
        sa.Column("last_modified", sa.Float(), nullable=False),
        sa.Column("hash_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("concept", "context_id", name=op.f("pk_nonebot_plugin_chat_memorynode")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    with op.batch_alter_table("nonebot_plugin_chat_chatgroup", schema=None) as batch_op:
        batch_op.drop_column("memory")

    with op.batch_alter_table("nonebot_plugin_chat_chatuser", schema=None) as batch_op:
        batch_op.drop_column("memory")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_chatuser", schema=None) as batch_op:
        batch_op.add_column(sa.Column("memory", sa.TEXT(), nullable=False))

    with op.batch_alter_table("nonebot_plugin_chat_chatgroup", schema=None) as batch_op:
        batch_op.add_column(sa.Column("memory", sa.TEXT(), nullable=False))

    op.drop_table("nonebot_plugin_chat_memorynode")
    op.drop_table("nonebot_plugin_chat_memoryedge")
    # ### end Alembic commands ###
