"""add unreplied count to private chat session

迁移 ID: 5b174323b47f
父迁移: df44b6f490e7
创建时间: 2026-08-03 07:50:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "5b174323b47f"
down_revision: str | Sequence[str] | None = "df44b6f490e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_privatechatsession", schema=None) as batch_op:
        batch_op.add_column(sa.Column("unreplied_count", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_privatechatsession", schema=None) as batch_op:
        batch_op.drop_column("unreplied_count")
    # ### end Alembic commands ###
