"""empty message

迁移 ID: 5e5d93afbc20
父迁移: c1d2e3f4a5b6
创建时间: 2026-02-09 22:16:22.822986

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "5e5d93afbc20"
down_revision: str | Sequence[str] | None = "c1d2e3f4a5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkcave_imagedata", schema=None) as batch_op:
        batch_op.drop_column("file_id")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkcave_imagedata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.VARCHAR(length=32), nullable=False))

    # ### end Alembic commands ###
