"""empty message

迁移 ID: 608f1ec0be0b
父迁移: 037dfa9894a4
创建时间: 2025-08-06 21:37:58.278708

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "608f1ec0be0b"
down_revision: str | Sequence[str] | None = "037dfa9894a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_everyday_wife_wifedata", schema=None) as batch_op:
        batch_op.alter_column("wife_id", existing_type=sa.VARCHAR(length=128), nullable=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_everyday_wife_wifedata", schema=None) as batch_op:
        batch_op.alter_column("wife_id", existing_type=sa.VARCHAR(length=128), nullable=False)

    # ### end Alembic commands ###
