"""empty message

迁移 ID: 623fed631343
父迁移: b280c1f25edc
创建时间: 2026-02-28 22:15:49.931313

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '623fed631343'
down_revision: str | Sequence[str] | None = 'b280c1f25edc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_last_seen_lastseenrecord',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'session_id', name=op.f('pk_nonebot_plugin_last_seen_lastseenrecord')),
    info={'bind_key': 'nonebot_plugin_last_seen'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_last_seen_lastseenrecord')
    # ### end Alembic commands ###
