"""empty message

迁移 ID: 6865664c438a
父迁移: 873df3033ef0
创建时间: 2026-04-26 09:52:21.649992

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6865664c438a'
down_revision: str | Sequence[str] | None = '873df3033ef0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_chatgroup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore_mention_user', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_chatgroup', schema=None) as batch_op:
        batch_op.drop_column('ignore_mention_user')

    # ### end Alembic commands ###
