"""add dropping_enabled to chat_group

迁移 ID: 69e42fc34f38
父迁移: 74ea37f64bfa
创建时间: 2026-05-13 11:54:20.256050

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "69e42fc34f38"
down_revision: str | Sequence[str] | None = "74ea37f64bfa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_larkcave_imagedata")
    op.drop_table("nonebot_plugin_larkcave_usercooldowndata")
    op.drop_table("nonebot_plugin_schedule_userschedule")
    op.drop_table("nonebot_plugin_email_emaildata")
    op.drop_table("nonebot_plugin_email_emailuser")
    op.drop_table("nonebot_plugin_achievement_user")
    op.drop_table("nonebot_plugin_quick_math_quickmathuser")
    op.drop_table("nonebot_plugin_larkcave_cavedata")
    op.drop_table("nonebot_plugin_sign_signdata")
    op.drop_table("nonebot_plugin_larkcave_removedcave")
    op.drop_table("nonebot_plugin_email_emailitem")
    op.drop_table("nonebot_plugin_larkcave_commentdata")
    with op.batch_alter_table("nonebot_plugin_chat_chatgroup", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dropping_enabled", sa.Boolean(), nullable=False))

    with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
        batch_op.alter_column(
            "message_hash", existing_type=sa.NUMERIC(precision=32), type_=sa.BINARY(length=32), existing_nullable=False
        )

    with op.batch_alter_table("nonebot_plugin_fight_character", schema=None) as batch_op:
        batch_op.alter_column("buff_list", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)
        batch_op.alter_column("equipment", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)
        batch_op.alter_column("talent_level", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_fight_equipmentdata", schema=None) as batch_op:
        batch_op.alter_column("gains", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_fight_playerteam", schema=None) as batch_op:
        batch_op.alter_column("character_list", existing_type=sa.BLOB(), type_=sa.Text(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_fight_playerteam", schema=None) as batch_op:
        batch_op.alter_column("character_list", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_fight_equipmentdata", schema=None) as batch_op:
        batch_op.alter_column("gains", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_fight_character", schema=None) as batch_op:
        batch_op.alter_column("talent_level", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)
        batch_op.alter_column("equipment", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)
        batch_op.alter_column("buff_list", existing_type=sa.Text(), type_=sa.BLOB(), existing_nullable=False)

    with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
        batch_op.alter_column(
            "message_hash", existing_type=sa.BINARY(length=32), type_=sa.NUMERIC(precision=32), existing_nullable=False
        )

    with op.batch_alter_table("nonebot_plugin_chat_chatgroup", schema=None) as batch_op:
        batch_op.drop_column("dropping_enabled")

    op.create_table(
        "nonebot_plugin_larkcave_commentdata",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("author", sa.VARCHAR(length=128), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("time", sa.DATETIME(), nullable=False),
        sa.Column("belong", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_commentdata")),
    )
    op.create_table(
        "nonebot_plugin_email_emailitem",
        sa.Column("id_", sa.INTEGER(), nullable=False),
        sa.Column("belong", sa.INTEGER(), nullable=False),
        sa.Column("item_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("count", sa.INTEGER(), nullable=False),
        sa.Column("data", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_email_emailitem")),
    )
    op.create_table(
        "nonebot_plugin_larkcave_removedcave",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("expiration_time", sa.DATETIME(), nullable=False),
        sa.Column("superuser", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remove_removedcave")),
    )
    op.create_table(
        "nonebot_plugin_sign_signdata",
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("sign_days", sa.INTEGER(), nullable=False),
        sa.Column("last_sign", sa.DATE(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_sign_signdata")),
    )
    op.create_table(
        "nonebot_plugin_larkcave_cavedata",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("author", sa.VARCHAR(length=128), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("time", sa.DATETIME(), nullable=False),
        sa.Column("public", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_larkcave_cavedata")),
    )
    op.create_table(
        "nonebot_plugin_quick_math_quickmathuser",
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("experience", sa.INTEGER(), nullable=False),
        sa.Column("exchanged", sa.INTEGER(), nullable=False),
        sa.Column("max_point", sa.INTEGER(), nullable=False),
        sa.Column("last_use", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_quick_math_quickmathuser")),
    )
    op.create_table(
        "nonebot_plugin_achievement_user",
        sa.Column("_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("achievement_namespace", sa.VARCHAR(length=32), nullable=False),
        sa.Column("achievement_path", sa.VARCHAR(length=32), nullable=False),
        sa.Column("unlock_progress", sa.INTEGER(), nullable=False),
        sa.Column("unlocked", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("_id", name=op.f("pk_nonebot_plugin_achievement_user")),
    )
    op.create_table(
        "nonebot_plugin_email_emailuser",
        sa.Column("id_", sa.INTEGER(), nullable=False),
        sa.Column("is_claimed", sa.BOOLEAN(), nullable=False),
        sa.Column("is_read", sa.BOOLEAN(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("email_id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_email_emailuser")),
    )
    op.create_table(
        "nonebot_plugin_email_emaildata",
        sa.Column("email_id", sa.INTEGER(), nullable=False),
        sa.Column("author", sa.VARCHAR(length=128), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("subject", sa.VARCHAR(length=256), nullable=False),
        sa.Column("time", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("email_id", name=op.f("pk_nonebot_plugin_email_emaildata")),
    )
    op.create_table(
        "nonebot_plugin_schedule_userschedule",
        sa.Column("id_", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("task_id", sa.VARCHAR(length=16), nullable=False),
        sa.Column("updated_at", sa.DATE(), nullable=False),
        sa.Column("completed_count", sa.INTEGER(), nullable=False),
        sa.Column("collected", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_schedule_userschedule")),
    )
    op.create_table(
        "nonebot_plugin_larkcave_usercooldowndata",
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("last_use", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_larkcave_usercooldowndata")),
    )
    op.create_table(
        "nonebot_plugin_larkcave_imagedata",
        sa.Column("id", sa.DOUBLE(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("belong", sa.INTEGER(), nullable=False),
        sa.Column("p_hash", sa.VARCHAR(length=64), nullable=True),
        sa.Column("image_data", sa.BLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_larkcave_imagedata")),
    )
    # ### end Alembic commands ###
