"""empty message

迁移 ID: 6b9703542c98
父迁移: 037dfa9894a4
创建时间: 2025-08-10 14:56:07.601013

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6b9703542c98"
down_revision: str | Sequence[str] | None = "037dfa9894a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_fight_character",
        sa.Column("character_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("get_time", sa.DateTime(), nullable=False),
        sa.Column("character_type", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("hp_percent", sa.Integer(), nullable=False),
        sa.Column("fav", sa.Float(), nullable=False),
        sa.Column("buff_list", sa.LargeBinary(), nullable=False),
        sa.Column("equipment", sa.LargeBinary(), nullable=False),
        sa.Column("talent_level", sa.LargeBinary(), nullable=False),
        sa.Column("weapon_experience", sa.Integer(), nullable=False),
        sa.Column("weapon_damage", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("character_id", name=op.f("pk_nonebot_plugin_fight_character")),
        info={"bind_key": "nonebot_plugin_fight"},
    )
    op.create_table(
        "nonebot_plugin_fight_equipmentdata",
        sa.Column("equipment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("equipment_type", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("gains", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("equipment_id", name=op.f("pk_nonebot_plugin_fight_equipmentdata")),
        info={"bind_key": "nonebot_plugin_fight"},
    )
    op.create_table(
        "nonebot_plugin_fight_playerteam",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("characters", sa.LargeBinary(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_fight_playerteam")),
        info={"bind_key": "nonebot_plugin_fight"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_fight_playerteam")
    op.drop_table("nonebot_plugin_fight_equipmentdata")
    op.drop_table("nonebot_plugin_fight_character")
    # ### end Alembic commands ###
