"""empty message

迁移 ID: 76ba80e8a2f0
父迁移: 01cf42b0eb35
创建时间: 2026-02-17 17:36:50.271014

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "76ba80e8a2f0"
down_revision: str | Sequence[str] | None = "01cf42b0eb35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # 清空表以避免重复键错误
    op.execute("DELETE FROM nonebot_plugin_larklang_languagekeycache")
    with op.batch_alter_table("nonebot_plugin_larklang_languagekeycache", schema=None) as batch_op:
        batch_op.drop_column("id_")
        batch_op.create_primary_key("pk_nonebot_plugin_larklang_languagekeycache", ["language", "plugin", "key"])

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larklang_languagekeycache", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id_", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint("pk_nonebot_plugin_larklang_languagekeycache", type_="primary")

    # ### end Alembic commands ###
