"""empty message

迁移 ID: 7bb4963dc8fc
父迁移: bffa83bd0147
创建时间: 2025-12-31 18:51:18.353475

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "7bb4963dc8fc"
down_revision: str | Sequence[str] | None = "bffa83bd0147"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_ba_calendar_bacremindersent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.BigInteger(), nullable=False),
        sa.Column("reminder_type", sa.String(length=16), nullable=False),
        sa.Column("server", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_ba_calendar_bacremindersent")),
        info={"bind_key": "nonebot_plugin_ba_calendar"},
    )
    op.create_table(
        "nonebot_plugin_ba_calendar_bacremindersubscription",
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("server", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_nonebot_plugin_ba_calendar_bacremindersubscription")),
        info={"bind_key": "nonebot_plugin_ba_calendar"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_ba_calendar_bacremindersubscription")
    op.drop_table("nonebot_plugin_ba_calendar_bacremindersent")
    # ### end Alembic commands ###
