"""empty message

迁移 ID: 7e2901072e70
父迁移: b2c3d4e5f6a7
创建时间: 2026-02-21 12:21:05.425800

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "7e2901072e70"
down_revision: str | Sequence[str] | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_proactivemessagerecord",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("sent_time", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_chat_proactivemessagerecord")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    with op.batch_alter_table("nonebot_plugin_chat_proactivemessagerecord", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_chat_proactivemessagerecord_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_proactivemessagerecord", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_chat_proactivemessagerecord_user_id"))

    op.drop_table("nonebot_plugin_chat_proactivemessagerecord")
    # ### end Alembic commands ###
