"""empty message

迁移 ID: 849b5b127800
父迁移: 15f6ccca4a5d
创建时间: 2025-09-05 23:18:13.787982

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "849b5b127800"
down_revision: str | Sequence[str] | None = "15f6ccca4a5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_larkuser_guestuser",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("nickname", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_larkuser_guestuser")),
        info={"bind_key": "nonebot_plugin_larkuser"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_larkuser_guestuser")
    # ### end Alembic commands ###
