"""empty message

迁移 ID: 873df3033ef0
父迁移: 1de90c8618db
创建时间: 2026-04-18 09:53:57.753440

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "873df3033ef0"
down_revision: str | Sequence[str] | None = "1de90c8618db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_mainsessionactionhistory",
        sa.Column("id_", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("action", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_chat_mainsessionactionhistory")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    op.drop_table("nonebot_plugin_chat_mainsessiondata")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_mainsessiondata",
        sa.Column("key", sa.VARCHAR(length=64), nullable=False),
        sa.Column("data_json", sa.TEXT(), nullable=False),
        sa.Column("updated_time", sa.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_nonebot_plugin_chat_mainsessiondata")),
    )
    op.drop_table("nonebot_plugin_chat_mainsessionactionhistory")
    # ### end Alembic commands ###
