"""empty message

迁移 ID: 880afb20f8fb
父迁移: 5c55ec8e050e
创建时间: 2025-07-13 09:59:42.579903

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "880afb20f8fb"
down_revision: str | Sequence[str] | None = "5c55ec8e050e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_chatuser",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("memory", sa.Text(), nullable=False),
        sa.Column("latest_chat", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_chat_chatuser")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    op.create_table(
        "nonebot_plugin_chat_sessionmessage",
        sa.Column("id_", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_chat_sessionmessage")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    op.drop_table("nonebot_plugin_openai_sessionmessage")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_openai_sessionmessage",
        sa.Column("message_id", sa.INTEGER(), nullable=False),
        sa.Column("session_id", sa.INTEGER(), nullable=False),
        sa.Column("content", sa.BLOB(), nullable=False),
        sa.Column("role", sa.VARCHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_nonebot_plugin_openai_sessionmessage")),
    )
    op.drop_table("nonebot_plugin_chat_sessionmessage")
    op.drop_table("nonebot_plugin_chat_chatuser")
    # ### end Alembic commands ###
