"""empty message

迁移 ID: 8862c8b07749
父迁移: b93186c3705a
创建时间: 2026-02-23 13:44:39.470513

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "8862c8b07749"
down_revision: str | Sequence[str] | None = "b93186c3705a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
        batch_op.drop_column("consecutive_bot_messages")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
        batch_op.add_column(sa.Column("consecutive_bot_messages", sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
