"""empty message

迁移 ID: 898d6147c141
父迁移: 09737ac938df
创建时间: 2024-08-22 23:10:10.062512

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '898d6147c141'
down_revision: str | Sequence[str] | None = '09737ac938df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_minigames_api_user',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('exchanged_pawcoin', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_minigames_api_user')),
    info={'bind_key': 'nonebot_plugin_minigames_api'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_minigames_api_user')
    # ### end Alembic commands ###
