"""empty message

迁移 ID: 8cc0b6be9f50
父迁移: 0778ae595d24
创建时间: 2025-08-23 22:26:28.373737

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "8cc0b6be9f50"
down_revision: str | Sequence[str] | None = "0778ae595d24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_online_timer_onlinetimerecord",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_online_timer_onlinetimerecord")),
        info={"bind_key": "nonebot_plugin_online_timer"},
    )
    with op.batch_alter_table("nonebot_plugin_online_timer_onlinetimerecord", schema=None) as batch_op:
        batch_op.create_index("idx_end_time", ["end_time"], unique=False)
        batch_op.create_index("idx_start_time", ["start_time"], unique=False)
        batch_op.create_index("idx_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_online_timer_onlinetimerecord_end_time"), ["end_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_online_timer_onlinetimerecord_start_time"), ["start_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_online_timer_onlinetimerecord_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_online_timer_onlinetimerecord", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_online_timer_onlinetimerecord_user_id"))
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_online_timer_onlinetimerecord_start_time"))
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_online_timer_onlinetimerecord_end_time"))
        batch_op.drop_index("idx_user_id")
        batch_op.drop_index("idx_start_time")
        batch_op.drop_index("idx_end_time")

    op.drop_table("nonebot_plugin_online_timer_onlinetimerecord")
    # ### end Alembic commands ###
