"""empty message

迁移 ID: 914ea7c45165
父迁移: 4c93ee7b18f3
创建时间: 2024-07-08 14:08:56.329908

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '914ea7c45165'
down_revision: str | Sequence[str] | None = '4c93ee7b18f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_email_emaildata',
    sa.Column('email_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email_id', name=op.f('pk_nonebot_plugin_email_emaildata')),
    info={'bind_key': 'nonebot_plugin_email'}
    )
    op.drop_table('nonebot_plugin_email_email')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_email_email',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_nonebot_plugin_email_email')
    )
    op.drop_table('nonebot_plugin_email_emaildata')
    # ### end Alembic commands ###
