"""empty message

迁移 ID: 9537565f5d31
父迁移: 9b5c83fbf91b
创建时间: 2024-07-21 21:35:58.040871

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "9537565f5d31"
down_revision: str | Sequence[str] | None = "9b5c83fbf91b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_wakatime_user",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("user_name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_wakatime_user")),
        info={"bind_key": "nonebot_plugin_wakatime"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_wakatime_user")
    # ### end Alembic commands ###
