"""empty message

迁移 ID: 959031f95873
父迁移: 3875dac35e58
创建时间: 2026-01-31 22:45:09.148770

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "959031f95873"
down_revision: str | Sequence[str] | None = "3875dac35e58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_messagequeuecache",
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.Column("messages_json", sa.Text(), nullable=False),
        sa.Column("consecutive_bot_messages", sa.Integer(), nullable=False),
        sa.Column("updated_time", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_nonebot_plugin_chat_messagequeuecache")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_chat_messagequeuecache")
    # ### end Alembic commands ###
