"""empty message

迁移 ID: 976041c1db98
父迁移: 2cd80b434c9c
创建时间: 2026-03-22 10:04:37.232805

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '976041c1db98'
down_revision: str | Sequence[str] | None = '2cd80b434c9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_bots_user_private_chat_settings',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('bot_id', sa.String(length=128), nullable=False),
    sa.Column('private_chat_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'bot_id', name=op.f('pk_nonebot_plugin_bots_user_private_chat_settings')),
    info={'bind_key': 'nonebot_plugin_bots'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_bots_user_private_chat_settings')
    # ### end Alembic commands ###
