"""empty message

迁移 ID: 97e8f2c58ae8
父迁移: bf58990827fc
创建时间: 2025-02-01 12:23:21.860562

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '97e8f2c58ae8'
down_revision: str | Sequence[str] | None = 'bf58990827fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_schedule_userschedule',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk_nonebot_plugin_schedule_userschedule')),
    info={'bind_key': 'nonebot_plugin_schedule'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_schedule_userschedule')
    # ### end Alembic commands ###
