"""empty message

迁移 ID: 9c6d165934aa
父迁移: a0ede4f55da2
创建时间: 2025-05-31 21:03:25.707694

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9c6d165934aa'
down_revision: str | Sequence[str] | None = 'a0ede4f55da2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_larkutils_luckvalue',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('luck_value', sa.Integer(), nullable=False),
    sa.Column('generate_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_larkutils_luckvalue')),
    info={'bind_key': 'nonebot_plugin_larkutils'}
    )
    op.drop_table('nonebot_plugin_pawcoin_exchange_exchanged')
    op.drop_table('nonebot_plugin_finding_the_trail_userpoint')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_finding_the_trail_userpoint',
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.Column('exchanged', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='pk_nonebot_plugin_finding_the_trail_userpoint')
    )
    op.create_table('nonebot_plugin_pawcoin_exchange_exchanged',
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('pawcoin', sa.INTEGER(), nullable=False),
    sa.Column('vimcoin', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='pk_nonebot_plugin_pawcoin_exchange_exchanged')
    )
    op.drop_table('nonebot_plugin_larkutils_luckvalue')
    # ### end Alembic commands ###
