"""新增市场插件

迁移 ID: 9f6eedd5686c
父迁移: ffdcbc994500
创建时间: 2025-08-14 13:39:38.284103

玩家间物品交易市场：`nonebot_plugin_market_marketitem` 保存上架中的商品
（item_data 以 JSON 文本保存物品 NBT），`nonebot_plugin_market_selllog`
按物品类型累计成交数量与成交金额，用于计算平均成交价。

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "9f6eedd5686c"
down_revision: str | Sequence[str] | None = "ffdcbc994500"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_market_marketitem",
        sa.Column("item_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_namespace", sa.String(length=64), nullable=False),
        sa.Column("remain_count", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("item_data", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("item_id", name=op.f("pk_nonebot_plugin_market_marketitem")),
        info={"bind_key": "nonebot_plugin_market"},
    )
    op.create_table(
        "nonebot_plugin_market_selllog",
        sa.Column("item_namespace", sa.String(length=64), nullable=False),
        sa.Column("sold_count", sa.Integer(), nullable=False),
        sa.Column("price_sum", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("item_namespace", name=op.f("pk_nonebot_plugin_market_selllog")),
        info={"bind_key": "nonebot_plugin_market"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_market_selllog")
    op.drop_table("nonebot_plugin_market_marketitem")
    # ### end Alembic commands ###
