"""update MessageQueueCache messages_json column to MEDIUMTEXT for MySQL

迁移 ID: a0af598a2bca
父迁移: cc1beaf0029b
创建时间: 2026-02-09 19:04:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "a0af598a2bca"
down_revision: str | Sequence[str] | None = "cc1beaf0029b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # 获取当前数据库方言
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "mysql":
        # MySQL: 将 messages_json 列从 TEXT (64KB) 改为 MEDIUMTEXT (16MB)
        from sqlalchemy.dialects.mysql import MEDIUMTEXT

        with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
            batch_op.alter_column("messages_json", existing_type=sa.TEXT(), type_=MEDIUMTEXT(), existing_nullable=False)
    # SQLite: 不需要操作，TEXT 没有大小限制
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # 获取当前数据库方言
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "mysql":
        # MySQL: 回滚为 TEXT
        from sqlalchemy.dialects.mysql import MEDIUMTEXT

        with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
            batch_op.alter_column("messages_json", existing_type=MEDIUMTEXT(), type_=sa.TEXT(), existing_nullable=False)
    # SQLite: 不需要操作
    # ### end Alembic commands ###
