"""empty message

迁移 ID: a0ede4f55da2
父迁移: 97e8f2c58ae8
创建时间: 2025-05-01 22:42:13.097850

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'a0ede4f55da2'
down_revision: str | Sequence[str] | None = '97e8f2c58ae8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_minigame_api_usergamedata',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('minigame_id', sa.String(length=32), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('play_seconds', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk_nonebot_plugin_minigame_api_usergamedata')),
    info={'bind_key': 'nonebot_plugin_minigame_api'}
    )
    with op.batch_alter_table('nonebot_plugin_minigame_api_usergamedata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_minigame_api_usergamedata_minigame_id'), ['minigame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_minigame_api_usergamedata_user_id'), ['user_id'], unique=False)

    op.drop_table('nonebot_plugin_minigames_api_user')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_minigames_api_user',
    sa.Column('user_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('total_points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exchanged_pawcoin', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seconds', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('nonebot_plugin_minigame_api_usergamedata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_minigame_api_usergamedata_user_id'))
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_minigame_api_usergamedata_minigame_id'))

    op.drop_table('nonebot_plugin_minigame_api_usergamedata')
    # ### end Alembic commands ###
