"""Add p_hash column to Sticker table for image deduplication

迁移 ID: a1b2c3d4e5f6
父迁移: ffdcbc994494
创建时间: 2026-01-15 13:30:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "a1b2c3d4e5f6"
down_revision: str | Sequence[str] | None = "ffdcbc994494"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.add_column(sa.Column("p_hash", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.drop_column("p_hash")
    # ### end Alembic commands ###