"""Add p_hash column to Sticker table for image deduplication

迁移 ID: a1b2c3d4e5f6
父迁移: ffdcbc994494
创建时间: 2026-01-15 13:30:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

revision: str = "a1b2c3d4e5f6"
down_revision: str | Sequence[str] | None = "ffdcbc994494"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    conn = op.get_bind()
    inspector = inspect(conn)
    if "nonebot_plugin_chat_sticker" not in inspector.get_table_names():
        # 另一条分支还没创建这张表，一起创建（带 p_hash 列）
        op.create_table(
            "nonebot_plugin_chat_sticker",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("description", sa.Text(), nullable=False),
            sa.Column("raw", sa.LargeBinary(), nullable=False),
            sa.Column("group_id", sa.String(length=128), nullable=True),
            sa.Column("created_time", sa.Float(), nullable=False),
            sa.Column("p_hash", sa.String(length=64), nullable=True),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_chat_sticker")),
        )
        with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_nonebot_plugin_chat_sticker_group_id"), ["group_id"], unique=False)
        return
    # 表已存在，检查 p_hash 列
    columns = [c["name"] for c in inspector.get_columns("nonebot_plugin_chat_sticker")]
    if "p_hash" in columns:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.add_column(sa.Column("p_hash", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.drop_column("p_hash")
    # ### end Alembic commands ###
