"""empty message

迁移 ID: a56ea9fea5af
父迁移: 8536e8703b40
创建时间: 2024-11-15 15:01:34.994751

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "a56ea9fea5af"
down_revision: str | Sequence[str] | None = "8536e8703b40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_larklang_displaysetting",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("theme", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_larklang_displaysetting")),
        info={"bind_key": "nonebot_plugin_larklang"},
    )
    op.create_table(
        "nonebot_plugin_larklang_languagekeycache",
        sa.Column("id_", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("plugin", sa.String(length=20), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("text", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_larklang_languagekeycache")),
        info={"bind_key": "nonebot_plugin_larklang"},
    )
    op.drop_table("nonebot_plugin_quick_math_quickmathuser")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_quick_math_quickmathuser",
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("total_point", sa.INTEGER(), nullable=False),
        sa.Column("max_point", sa.INTEGER(), nullable=False),
        sa.Column("last_use", sa.DATETIME(), nullable=False),
        sa.Column("max_point_this_cycle", sa.INTEGER(), nullable=False),
        sa.Column("use_count_this_cycle", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name="pk_nonebot_plugin_quick_math_quickmathuser"),
    )
    op.drop_table("nonebot_plugin_larklang_languagekeycache")
    op.drop_table("nonebot_plugin_larklang_displaysetting")
    # ### end Alembic commands ###
