"""empty message

迁移 ID: a7ce3ee38208
父迁移: 7bb4963dc8fc
创建时间: 2025-12-31 20:16:00.783619

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "a7ce3ee38208"
down_revision: str | Sequence[str] | None = "7bb4963dc8fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_userprofile",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("profile_content", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_chat_userprofile")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_chat_userprofile")
    # ### end Alembic commands ###
