"""add timestamp to GroupMessage

迁移 ID: add_timestamp_to_groupmessage
父迁移: 36722c1b0659
创建时间: 2025-08-17 12:00:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from datetime import datetime


revision: str = "add_timestamp_to_groupmessage"
down_revision: str | Sequence[str] | None = "36722c1b0659"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nonebot_plugin_message_summary_groupmessage",
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        info={"bind_key": "nonebot_plugin_message_summary"},
    )
    
    # Update existing rows to have current timestamp
    op.execute(
        "UPDATE nonebot_plugin_message_summary_groupmessage SET timestamp = datetime('now') WHERE timestamp IS NULL"
    )
    
    # Make the column non-nullable after updating existing data
    op.alter_column(
        "nonebot_plugin_message_summary_groupmessage",
        "timestamp",
        nullable=False,
        info={"bind_key": "nonebot_plugin_message_summary"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "nonebot_plugin_message_summary_groupmessage",
        "timestamp",
        info={"bind_key": "nonebot_plugin_message_summary"},
    )
    # ### end Alembic commands ###