"""empty message

迁移 ID: ae4bd9cc1635
父迁移: a7ce3ee38208
创建时间: 2025-12-31 21:28:29.476669

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "ae4bd9cc1635"
down_revision: str | Sequence[str] | None = "a7ce3ee38208"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_sticker",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("raw", sa.LargeBinary(), nullable=False),
        sa.Column("group_id", sa.String(length=128), nullable=True),
        sa.Column("created_time", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_chat_sticker")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nonebot_plugin_chat_sticker_group_id"), ["group_id"], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_chat_sticker_group_id"))

    op.drop_table("nonebot_plugin_chat_sticker")
    # ### end Alembic commands ###
