"""empty message

迁移 ID: b280c1f25edc
父迁移: 8862c8b07749
创建时间: 2026-02-23 21:49:49.956601

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "b280c1f25edc"
down_revision: str | Sequence[str] | None = "8862c8b07749"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_larklang_grouplanguagesetting",
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_nonebot_plugin_larklang_grouplanguagesetting")),
        info={"bind_key": "nonebot_plugin_larklang"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_larklang_grouplanguagesetting")
    # ### end Alembic commands ###
