"""empty message

迁移 ID: b29767cc9c3d
父迁移: 623fed631343
创建时间: 2026-03-07 00:29:07.315652

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b29767cc9c3d'
down_revision: str | Sequence[str] | None = '623fed631343'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_proactivemessagerecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_chat_proactivemessagerecord_user_id'))

    op.drop_table('nonebot_plugin_chat_proactivemessagerecord')
    with op.batch_alter_table('nonebot_plugin_chat_privatechatsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_proactive_message_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_privatechatsession', schema=None) as batch_op:
        batch_op.drop_column('last_proactive_message_time')

    op.create_table('nonebot_plugin_chat_proactivemessagerecord',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('sent_time', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_chat_proactivemessagerecord'))
    )
    with op.batch_alter_table('nonebot_plugin_chat_proactivemessagerecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_chat_proactivemessagerecord_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
