"""empty message

迁移 ID: b93186c3705a
父迁移: 76ba80e8a2f0
创建时间: 2026-02-21 11:47:28.848351

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b93186c3705a'
down_revision: str | Sequence[str] | None = '76ba80e8a2f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_openai_openaimodelconfig',
    sa.Column('config_key', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('config_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('config_key', name=op.f('pk_nonebot_plugin_openai_openaimodelconfig')),
    info={'bind_key': 'nonebot_plugin_openai'}
    )
    op.drop_table('nonebot_plugin_openai_modelconfig')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_openai_modelconfig',
    sa.Column('config_key', sa.VARCHAR(length=256), nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('config_type', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.drop_table('nonebot_plugin_openai_openaimodelconfig')
    # ### end Alembic commands ###
