"""add command_usage table

迁移 ID: bc900b880f83
父迁移: 0fbe94039ef4
创建时间: 2026-05-29 21:20:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc900b880f83"
down_revision: str | Sequence[str] | None = "0fbe94039ef4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("command", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("group_id", sa.String(length=128), nullable=True),
        sa.Column("used_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # 创建索引以优化查询性能
    with op.batch_alter_table("command_usage", schema=None) as batch_op:
        batch_op.create_index("ix_command_usage_command", ["command"])
        batch_op.create_index("ix_command_usage_user_id", ["user_id"])
        batch_op.create_index("ix_command_usage_group_id", ["group_id"])
        batch_op.create_index("ix_command_usage_used_at", ["used_at"])
        batch_op.create_index("ix_command_usage_used_at_command", ["used_at", "command"])

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("command_usage", schema=None) as batch_op:
        batch_op.drop_index("ix_command_usage_used_at_command")
        batch_op.drop_index("ix_command_usage_used_at")
        batch_op.drop_index("ix_command_usage_group_id")
        batch_op.drop_index("ix_command_usage_user_id")
        batch_op.drop_index("ix_command_usage_command")

    op.drop_table("command_usage")
    # ### end Alembic commands ###
