"""empty message

迁移 ID: bf58990827fc
父迁移: 70f7d8846114
创建时间: 2025-01-28 11:37:14.104759

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'bf58990827fc'
down_revision: str | Sequence[str] | None = '70f7d8846114'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_commentdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('belong', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_commentdata')),
    info={'bind_key': 'comment'}
    )
    op.create_table('remove_removedcave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=False),
    sa.Column('superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remove_removedcave')),
    info={'bind_key': 'remove'}
    )
    op.drop_table('nonebot_plugin_cave_remove_removedcave')
    op.drop_table('nonebot_plugin_cave_comment_commentdata')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_cave_comment_commentdata',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('belong', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nonebot_plugin_cave_remove_removedcave',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('expiration_time', mysql.DATETIME(), nullable=False),
    sa.Column('superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('remove_removedcave')
    op.drop_table('comment_commentdata')
    # ### end Alembic commands ###
