"""empty message

迁移 ID: bffa83bd0147
父迁移: 3bab0285033f
创建时间: 2025-10-02 14:12:48.167478

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "bffa83bd0147"
down_revision: str | Sequence[str] | None = "3bab0285033f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_note", schema=None) as batch_op:
        batch_op.alter_column("expire_time", existing_type=sa.FLOAT(), type_=sa.DateTime(), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_note", schema=None) as batch_op:
        batch_op.alter_column("expire_time", existing_type=sa.DateTime(), type_=sa.FLOAT(), existing_nullable=True)

    # ### end Alembic commands ###
