"""add session metadata to larkuid sessiondata

为 Web 登录会话补充元数据列，支撑滑动过期、绝对寿命上限与设备管理：

- created_at: 会话创建时间（UTC），作为绝对寿命上限的锚点，也供未激活清理任务扫描；
- last_active_at: 最后活跃时间，滑动过期写入与设备管理展示共用；
- device: 设备描述（User-Agent 截断），仅用于设备管理列表展示。

三列均可空以兼容存量数据：存量行缺少 created_at 时不套用绝对上限，
行为与升级前一致。

迁移 ID: c3760946c865
父迁移: 0841fcf990e5
创建时间: 2026-08-03

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "c3760946c865"
down_revision: str | Sequence[str] | None = "0841fcf990e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkuid_sessiondata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_active_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("device", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkuid_sessiondata", schema=None) as batch_op:
        batch_op.drop_column("device")
        batch_op.drop_column("last_active_at")
        batch_op.drop_column("created_at")
    # ### end Alembic commands ###
