"""empty message

迁移 ID: cc1beaf0029b
父迁移: 959031f95873
创建时间: 2026-02-06 22:12:37.018892

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "cc1beaf0029b"
down_revision: str | Sequence[str] | None = "959031f95873"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_ruadata",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("action_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_nonebot_plugin_chat_ruadata")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_chat_ruadata")
    # ### end Alembic commands ###
