"""empty message

迁移 ID: cd0fa72bdd5d
父迁移: e9746d85ff25
创建时间: 2024-11-15 16:38:33.591337

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cd0fa72bdd5d'
down_revision: str | Sequence[str] | None = 'e9746d85ff25'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_larklang_languagekeycache', schema=None) as batch_op:
        batch_op.alter_column('plugin',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_larklang_languagekeycache', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('plugin',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
