"""empty message

迁移 ID: d025fa75554d
父迁移: 7e2901072e70
创建时间: 2026-02-21 12:30:12.592073

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd025fa75554d'
down_revision: str | Sequence[str] | None = '7e2901072e70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_chat_privatechatsession',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('bot_id', sa.String(length=128), nullable=False),
    sa.Column('last_message_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_chat_privatechatsession')),
    info={'bind_key': 'nonebot_plugin_chat'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_chat_privatechatsession')
    # ### end Alembic commands ###
