"""empty message

迁移 ID: d97df8840d07
父迁移: b29767cc9c3d
创建时间: 2026-03-20 13:01:54.499508

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "d97df8840d07"
down_revision: str | Sequence[str] | None = "b29767cc9c3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkutils_luckvalue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reroll_count", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_larkutils_luckvalue", schema=None) as batch_op:
        batch_op.drop_column("reroll_count")

    # ### end Alembic commands ###
