"""empty message

迁移 ID: dd2e135e7717
父迁移: 8cc0b6be9f50
创建时间: 2025-12-27 17:04:38.737650

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "dd2e135e7717"
down_revision: str | Sequence[str] | None = "8cc0b6be9f50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_chat_memorynode")
    op.drop_table("nonebot_plugin_chat_memoryedge")
    with op.batch_alter_table("nonebot_plugin_chat_note", schema=None) as batch_op:
        batch_op.alter_column("keywords", existing_type=sa.TEXT(), type_=sa.String(length=256), existing_nullable=False)
        batch_op.drop_column("hash_value")

    # 清空nonebot_plugin_chat_note表
    # 根据数据库类型选择不同的清空表命令
    bind = op.get_bind()
    if bind.dialect.name == "mysql":
        op.execute("TRUNCATE TABLE nonebot_plugin_chat_note")
    else:  # SQLite和其他数据库使用DELETE FROM
        op.execute("DELETE FROM nonebot_plugin_chat_note")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_note", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hash_value", sa.BIGINT(), nullable=False))
        batch_op.alter_column("keywords", existing_type=sa.String(length=256), type_=sa.TEXT(), existing_nullable=False)

    op.create_table(
        "nonebot_plugin_chat_memoryedge",
        sa.Column("source", sa.VARCHAR(length=256), nullable=False),
        sa.Column("target", sa.VARCHAR(length=256), nullable=False),
        sa.Column("context_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("strength", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.FLOAT(), nullable=False),
        sa.Column("last_modified", sa.FLOAT(), nullable=False),
        sa.Column("hash_value", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("source", "target", "context_id", name=op.f("pk_nonebot_plugin_chat_memoryedge")),
    )
    op.create_table(
        "nonebot_plugin_chat_memorynode",
        sa.Column("concept", sa.VARCHAR(length=256), nullable=False),
        sa.Column("context_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("memory_items", sa.TEXT(), nullable=False),
        sa.Column("weight", sa.FLOAT(), nullable=False),
        sa.Column("created_time", sa.FLOAT(), nullable=False),
        sa.Column("last_modified", sa.FLOAT(), nullable=False),
        sa.Column("hash_value", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("concept", "context_id", name=op.f("pk_nonebot_plugin_chat_memorynode")),
    )
    # ### end Alembic commands ###
