"""empty message

迁移 ID: dd4f522edf5d
父迁移: f79433854a65
创建时间: 2025-08-17 12:52:04.443435

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "dd4f522edf5d"
down_revision: str | Sequence[str] | None = "f79433854a65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_message_summary_groupmessage", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timestamp", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_message_summary_groupmessage", schema=None) as batch_op:
        batch_op.drop_column("timestamp")

    # ### end Alembic commands ###
