"""add session event model

迁移 ID: df44b6f490e7
父迁移: 991019747839
创建时间: 2026-07-29 10:28:44.714337

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "df44b6f490e7"
down_revision: str | Sequence[str] | None = "991019747839"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_sessionevent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("date", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_chat_sessionevent")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    with op.batch_alter_table("nonebot_plugin_chat_sessionevent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nonebot_plugin_chat_sessionevent_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_nonebot_plugin_chat_sessionevent_session_id"), ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_sessionevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_chat_sessionevent_session_id"))
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_chat_sessionevent_date"))

    op.drop_table("nonebot_plugin_chat_sessionevent")
    # ### end Alembic commands ###
