"""empty message

迁移 ID: e0034ee76dbc
父迁移: 880afb20f8fb
创建时间: 2025-07-19 12:28:58.843900

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e0034ee76dbc'
down_revision: str | Sequence[str] | None = '880afb20f8fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_larkuser_userdata', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('ship_code')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_larkuser_userdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_code', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
