"""empty message

迁移 ID: e59556a7ca0c
父迁移: 6865664c438a
创建时间: 2026-04-30 19:04:17.588138

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "e59556a7ca0c"
down_revision: str | Sequence[str] | None = "6865664c438a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_everyday_wife_wifedata")
    with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
        batch_op.add_column(sa.Column("message_id", sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(
            sa.Column("message_json", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=False)
        )
        batch_op.add_column(sa.Column("message_hash", sa.BINARY(length=32), nullable=False))
        batch_op.alter_column("updated_time", existing_type=sa.FLOAT(), type_=sa.DateTime(), existing_nullable=False)
        batch_op.drop_column("messages_json")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_chat_messagequeuecache", schema=None) as batch_op:
        batch_op.add_column(sa.Column("messages_json", sa.TEXT(), nullable=False))
        batch_op.alter_column("updated_time", existing_type=sa.DateTime(), type_=sa.FLOAT(), existing_nullable=False)
        batch_op.drop_column("message_hash")
        batch_op.drop_column("message_json")
        batch_op.drop_column("message_id")

    op.create_table(
        "nonebot_plugin_everyday_wife_wifedata",
        sa.Column("id_", sa.INTEGER(), nullable=False),
        sa.Column("group_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("wife_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("queried", sa.BOOLEAN(), nullable=False),
        sa.Column("generate_date", sa.DATE(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_nonebot_plugin_everyday_wife_wifedata")),
    )
    # ### end Alembic commands ###
