"""empty message

迁移 ID: e9746d85ff25
父迁移: a56ea9fea5af
创建时间: 2024-11-16 00:12:38.062936

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "e9746d85ff25"
down_revision: str | Sequence[str] | None = "a56ea9fea5af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_quick_math_quickmathuser", schema=None) as batch_op:
        batch_op.add_column(sa.Column("experience", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("exchanged", sa.Integer(), nullable=False))
        batch_op.drop_column("use_count_this_cycle")
        batch_op.drop_column("total_point")
        batch_op.drop_column("max_point_this_cycle")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_quick_math_quickmathuser", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_point_this_cycle", mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("total_point", mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("use_count_this_cycle", mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column("exchanged")
        batch_op.drop_column("experience")

    # ### end Alembic commands ###
