"""empty message

迁移 ID: ebd58910367a
父迁移: e7f8a9b0c1d2
创建时间: 2026-05-18 23:28:42.316324

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'ebd58910367a'
down_revision: str | Sequence[str] | None = 'e7f8a9b0c1d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_instantmemorycache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instantmemorycache_expire_time'))
        batch_op.drop_index(batch_op.f('ix_instantmemorycache_session_id'))
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_chat_instantmemorycache_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('nonebot_plugin_chat_privatechatsession', schema=None) as batch_op:
        batch_op.alter_column('session_key',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_chat_privatechatsession', schema=None) as batch_op:
        batch_op.alter_column('session_key',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('nonebot_plugin_chat_instantmemorycache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_chat_instantmemorycache_session_id'))
        batch_op.create_index(batch_op.f('ix_instantmemorycache_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instantmemorycache_expire_time'), ['expire_time'], unique=False)

    # ### end Alembic commands ###
