"""empty message

迁移 ID: f79433854a65
父迁移: 6b9703542c98
创建时间: 2025-08-10 17:16:32.816662

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f79433854a65'
down_revision: str | Sequence[str] | None = '6b9703542c98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_fight_playerteam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_list', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('characters')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_fight_playerteam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('characters', sa.BLOB(), nullable=False))
        batch_op.drop_column('character_list')

    # ### end Alembic commands ###
