"""update sticker raw column to MEDIUMBLOB

迁移 ID: f92937307e7a
父迁移: ae4bd9cc1635
创建时间: 2025-12-31 21:36:04.443090

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


revision: str = "f92937307e7a"
down_revision: str | Sequence[str] | None = "ae4bd9cc1635"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # 将 raw 列从 BLOB (64KB) 改为 MEDIUMBLOB (16MB)
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.alter_column(
            "raw", existing_type=sa.LargeBinary(), type_=sa.LargeBinary(length=16777215), existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚：将 raw 列从 MEDIUMBLOB 改回 BLOB
    with op.batch_alter_table("nonebot_plugin_chat_sticker", schema=None) as batch_op:
        batch_op.alter_column(
            "raw", existing_type=sa.LargeBinary(length=16777215), type_=sa.LargeBinary(), existing_nullable=False
        )
    # ### end Alembic commands ###
