"""update sticker raw column to MEDIUMBLOB for MySQL

迁移 ID: f92937307e7a
父迁移: ae4bd9cc1635
创建时间: 2025-12-31 21:36:04.443090

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f92937307e7a'
down_revision: str | Sequence[str] | None = 'ae4bd9cc1635'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # 获取当前数据库方言
    bind = op.get_bind()
    dialect = bind.dialect.name
    
    if dialect == 'mysql':
        # MySQL: 将 raw 列从 BLOB (64KB) 改为 MEDIUMBLOB (16MB)
        from sqlalchemy.dialects.mysql import MEDIUMBLOB
        with op.batch_alter_table('nonebot_plugin_chat_sticker', schema=None) as batch_op:
            batch_op.alter_column('raw',
                                  existing_type=sa.LargeBinary(),
                                  type_=MEDIUMBLOB(),
                                  existing_nullable=False)
    # SQLite: 不需要操作，BLOB 没有大小限制
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # 获取当前数据库方言
    bind = op.get_bind()
    dialect = bind.dialect.name
    
    if dialect == 'mysql':
        # MySQL: 回滚为 BLOB
        from sqlalchemy.dialects.mysql import MEDIUMBLOB
        with op.batch_alter_table('nonebot_plugin_chat_sticker', schema=None) as batch_op:
            batch_op.alter_column('raw',
                                  existing_type=MEDIUMBLOB(),
                                  type_=sa.LargeBinary(),
                                  existing_nullable=False)
    # SQLite: 不需要操作
    # ### end Alembic commands ###
