"""empty message

迁移 ID: fc68a41a83f3
父迁移: e0034ee76dbc
创建时间: 2025-07-24 00:25:51.436036

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "fc68a41a83f3"
down_revision: str | Sequence[str] | None = "e0034ee76dbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chat_chatgroup",
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.Column("memory", sa.Text(), nullable=False),
        sa.Column("blocked_user", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_nonebot_plugin_chat_chatgroup")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_chat_chatgroup")
    # ### end Alembic commands ###
