"""empty message

迁移 ID: ffdcbc994494
父迁移: dd2e135e7717
创建时间: 2026-01-02 00:59:21.549755

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "ffdcbc994494"
down_revision: str | Sequence[str] | None = "dd2e135e7717"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_time_progress_timeprogresssubscription",
        sa.Column("group_id", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_sent_year", sa.Integer(), nullable=False),
        sa.Column("last_sent_percentage", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_nonebot_plugin_time_progress_timeprogresssubscription")),
        info={"bind_key": "nonebot_plugin_time_progress"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_time_progress_timeprogresssubscription")
    # ### end Alembic commands ###
