"""Remove traditional memory fields and add graph-based memory

迁移 ID: lubapdd35b08
父迁移: fc68a41a83f3
创建时间: 2025-08-22 15:43:39.612573

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "lubapdd35b08"
down_revision: str | Sequence[str] | None = "fc68a41a83f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create memory graph tables
    op.create_table(
        "nonebot_plugin_chat_memorynode",
        sa.Column("concept", sa.String(length=256), nullable=False),
        sa.Column("context_id", sa.String(length=128), nullable=False),
        sa.Column("memory_items", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("created_time", sa.Float(), nullable=False),
        sa.Column("last_modified", sa.Float(), nullable=False),
        sa.Column("hash_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("concept", "context_id", name=op.f("pk_nonebot_plugin_chat_memorynode")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    
    op.create_table(
        "nonebot_plugin_chat_memoryedge",
        sa.Column("source", sa.String(length=256), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=False),
        sa.Column("context_id", sa.String(length=128), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.Float(), nullable=False),
        sa.Column("last_modified", sa.Float(), nullable=False),
        sa.Column("hash_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("source", "target", "context_id", name=op.f("pk_nonebot_plugin_chat_memoryedge")),
        info={"bind_key": "nonebot_plugin_chat"},
    )
    
    # Remove memory field from ChatUser table
    try:
        op.drop_column("nonebot_plugin_chat_chatuser", "memory")
    except Exception:
        pass  # Column might not exist
    
    # Remove memory field from ChatGroup table  
    try:
        op.drop_column("nonebot_plugin_chat_chatgroup", "memory")
    except Exception:
        pass  # Column might not exist
    
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back memory fields
    try:
        op.add_column("nonebot_plugin_chat_chatuser", sa.Column("memory", sa.Text(), nullable=False, default="None"))
    except Exception:
        pass
        
    try:
        op.add_column("nonebot_plugin_chat_chatgroup", sa.Column("memory", sa.Text(), nullable=False, default="暂无"))
    except Exception:
        pass
    
    # Drop memory graph tables
    op.drop_table("nonebot_plugin_chat_memoryedge")
    op.drop_table("nonebot_plugin_chat_memorynode")
    
    # ### end Alembic commands ###